### ISSUE TITLE
Why isn't prestashop:1.7-7.3-apache using 1.7.7?

### ISSUE THREAD

**Issue by xpavp03** [PrestaShop/docker#238]
I'm puzzled why 1.7-7.3-apache installs 1.7.6.8 which isn't compatible with PHP 7.3.

The only other option for PHP 7.3 are the nightly builds.
nightly-7.3-apache installs 1.7.8.0

I found 1.7.7 on your internal Docker images but I'd like to use some stable version. It's a dev environment but still.
https://hub.docker.com/r/prestashop/docker-internal-images

Thank you for your time.

**Comment by matks** [comment]
Hi, it's because 1.7.7.0 is not stable yet. We have a Release Candidate and hope to deliver a Stable Release soon (see https://build.prestashop.com/news/prestashop-1-7-7-0-rc-release/) but until then, the "latest stable" PrestaShop release is 1.7.6.8

This is likely to happen in November (unless very bad bugs are found inside the Release Candidate) 😊
