### ISSUE TITLE
Use modern php versions instead of php5.6

### ISSUE THREAD

**Issue by matks** [PrestaShop/docker#249]
By default, our images are running with PHP 5.6. But php5.6 is very old and not even supported by recent PrestaShop versions.

I suggest to provide docker images for PS versions >=1.7.5 with php7.1. Wdyt ?

**Comment by PierreRambaud** [comment]
I'm not in favor of changing all our old images. We are already doing it for all new images since the latest refactoring.

**Comment by matks** [comment]
@PierreRambaud I understand. Can you tell the motivation behind this?
- is this because you dont want people using our images to be affected by a change (changing php version could hurt some people CI)
- is it because you consider these versions are obsolete

**Comment by PierreRambaud** [comment]
Consider docker tag like git tag, if you create a tag, you don't have to change it in the future, you create a new version if needed.
With this in mind, it could be ok to create a `1.7.5.0-7.1-apache`, but this version is outdated, if we do it for a range of version, why not doing it for all versions.
Just because we don't maintain anymore everything around these images.
For example, if you check what Docker does with [Wordpress](https://hub.docker.com/_/wordpress) they never update their old images. It costs time and can break a lot of instances or CI already used by the community.

If you need something specific, you can rewrite the image and create your own PrestaShop images:

```
FROM prestashop/base:MY_PHP_VERSION-apache
LABEL maintainer="PrestaShop Core Team <coreteam@prestashop.com>"
ENV PS_VERSION MY_PRESTASHOP_VERSION
# Get PrestaShop
ADD https://www.prestashop.com/download/old/prestashop_MY_PRESTASHOP_VERSION.zip /tmp/prestashop.zip
# Extract
RUN mkdir -p /tmp/data-ps \
	&& unzip -q /tmp/prestashop.zip -d /tmp/data-ps/ \
	&& bash /tmp/ps-extractor.sh /tmp/data-ps \
	&& rm /tmp/prestashop.zip
```

The Dockerfile is really simple and can be easily customized

**Comment by matks** [comment]
@PierreRambaud I can build my own image, but I will have to host in dockerhub to be able to fetch it in Travis when running module autoupgrade builds 🤔  .

But I agree this is "my" problem, and this is out of this repository scope.

**Comment by PierreRambaud** [comment]
> @PierreRambaud I can build my own image, but I will have to host in dockerhub to be able to fetch it in Travis when running module autoupgrade builds  .
> 
> But I agree this is "my" problem, and this is out of this repository scope.

Not you don't need to have your own docker registry. You can build images locally and use it, it's quite easy and fast :wink:

**Comment by matks** [comment]
> Not you don't need to have your own docker registry. You can build images locally and use it, it's quite easy and fast 😉

But that would mean
- embed my own docker images inside https://github.com/prestashop/autoupgrade
- build them in Travis
- use them in Travis

Is it ... okay ? I dont want to "overload" autoupgrade repository with my docker-test-stuff ?

**Comment by PierreRambaud** [comment]
This is normal, we already do that in the Core.

It will let you do whatever you want, and allow you to have a custom instance.
Regarding what the autoupgrade need to do, you can upgrade from 1.7.0.0 to 1.7.7.0, all files and upgrade scripts will be executed during the whole upgrade process
