### ISSUE TITLE
Recursive write permissions missing

### ISSUE THREAD

**Issue by julianxhokaxhiu** [PrestaShop/docker#50]
Hi,

first of all let me thank for this awesome Docker. It's always great to see an official software supporting new stack of tecnologies.

Although, using your Docker and binding volumes ( the one listed inside your Dockerfile ) during the installation this is returned:

![prestashop](https://cloud.githubusercontent.com/assets/1237070/21568247/43b5926e-ceb3-11e6-96df-bfeeba2dfd44.png)

Can you consider [moving this line](https://github.com/PrestaShop/docker/blob/master/config_files/docker_run.sh#L76) outside that IF clause? Would really gives the user the possibility to do the installation also by hand :)

Thank you in advance,
Julian

---

CLI used:
```
docker run \
    -d \
    --restart=always \
    -e "ADMIN_MAIL=$ADMIN_MAIL" \
    -e "ADMIN_PASSWD=$ADMIN_PASSWD" \
    -v "/srv/modules:/var/www/html/modules" \
    -v "/srv/themes:/var/www/html/themes" \
    -v "/srv/override:/var/www/html/override" \
    prestashop/prestashop:1.6 &>/dev/null
```

**Comment by Quetzacoalt91** [comment]
Hello @julianxhokaxhiu,

I brought your suggestion to the project. I hope it will work better for your now. :)

Best regards

**Comment by julianxhokaxhiu** [comment]
Thank you very much! :D

Best regards,
Julian

**Comment by julianxhokaxhiu** [comment]
Sorry to bother you again but the issue is still there if I upload new files into the directory.

This line ( https://github.com/PrestaShop/docker/blob/master/config_files/docker_run.sh#L77 ) imho must be moved after the `fi` otherwise will be run if I am doing a fresh installation.

Can you please fix it?

Thanks in advance!

**Comment by Quetzacoalt91** [comment]
Hello,

Anyfile added by the webserver running in the container will have the proper owner.
If you manually insert your files (copy paste, wget with another user ...), you obviously have to change the owner by yourself, like on any Unix environment.

I agree to execute it at the first start in order to initialize the volumes with the proper user, but it seems unusual to override the files owner at each start. We never know, many one of them has been especially set during the shop runtime.

Best regards
